// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "heroSideAttackRight":
            case "anim1":return [img`
........................
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef...cc.......
.ffffee2222ef.cdc.......
.fe222ffffe2fcddc.......
fffffffeeeffcddc........
ffe44ebf44ecddc.........
fee4d41fddecdc..........
.feee4dddedccc..........
..ffee44e4dde...........
...f222244ee............
...f2222e2f.............
...f444455f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
.......fff..............
....fffff2f.............
..ffeeeee22ff...........
.ffeeeeee222ff..........
.feeeefffeeeef..........
.fffffeee2222ef.........
fffe222fffffe2f.........
fffffffffeeefff.....cc..
fefe44ebbf44eef...ccdc..
.fee4d4bbfddef..ccddcc..
..feee4dddddfeecdddc....
...f2222222eeddcdcc.....
...f444445e44ddccc......
...ffffffffeeee.........
...fff...ff.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
